version: '3.3'
services:
  waha:
    image: devlikeapro/waha:arm
    restart: always
    environment:
      - WAHA_API_KEY=secret_api_key_123
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=secret_password_123
      - WHATSAPP_API_SCHEMA=https
      - WAHA_PRINT_QR=false
    ports:
      - "3001:3000"
    volumes:
      - ./waha-data:/app/sessions
